### PR TITLE
Made Smash work with ESL files

### PR DESCRIPTION
**Pull request by gutfuckllc**
And updated xedit library to latest version.

### CODE REVIEW

**Comment by bmcclure** [comment]
Is this working in practice? It sure would be great to get something like this in an actual release, and it seems you've done a lot of the work already here.

**Comment by gutfuckllc** [comment]
All I did was pull the latest TES5Edit library source code (as of the pull date) and merged it alongside removed the code that stopped ESLs from being smashed.

It's working, however IIRC it still doesn't make esls really good for compatibility patches as ESLs cannot override an ESP's FORMID no matter what you do.

So, short thing short, yes but it's fiddly and not very useful either ways.

**Comment by steve25469** [comment]
Is there any info you can give on how exactly to go about doing this? I would love to do some testing with it, the lack of ESL support in mator smash has been a major issue for me.

**Comment by gutfuckllc** [comment]
I updated the Xedit library and removed the esl restriction.

That's it.

**Pull request closed without merging**
