### PR TITLE
Feature branch - Search + ShowHide Everything

### PR DESCRIPTION
**Pull request by Dakraid**
This integrates a search feature for the records-tree as well as a simple new context menu option to expand/collapse every node within the records-tree.

### CODE REVIEW

**Comment by matortheeternal** [comment]
Alright, I'll take a look!

**Comment by matortheeternal** [comment]
Taking a look.

**Comment by matortheeternal** [comment]
- If I defocus the Settings Manager form and focus it again, I can't continue my search from the same position (pressing enter does nothing).
- There's no indication of how many search results were found, or which one I'm on out of the results (might be nice)
- The form beeps every time I press enter.  You need to handle the input to mute the beep to properly communicate the user that you're handling it.  (the beep is a Windows feature saying input wasn't handled)

**Comment by matortheeternal** [comment]
The search text should reset to "Search..." when I change the setting selection.

**Comment by matortheeternal** [comment]
It would be cool if I could focus the search TEdit by pressing Ctrl+F.

**Comment by Dakraid** [comment]
Ok, sorry for abandoning the boat so soon. I will get Delphi installed soon again and fix this open PR. After that I should be able to properly contribute again in the near future. Sorry for the massive delay.

**Comment by Dakraid** [comment]
A more recent and improved PR can be found here: https://github.com/matortheeternal/smash/pull/131

**Pull request closed without merging**
